directories:
  output: release
  buildResources: build
appId: com.quing.terminal
productName: terminal by Quing
extraResources:
  - from: src/assets/Quing Logo 512.ico
    to: assets/Quing Logo 512.ico
files:
  - filter:
      - dist/**/*
      - electron/**/*
      - node_modules/**/*
      - package.json
win:
  target: nsis
  icon: src/assets/Quing Logo 512.ico
electronVersion: 41.0.2
